#pragma once

// WIFI
#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASS "YOUR_WIFI_PASSWORD"

// APRS
#define APRS_PASS "YOUR_APRS_PASS"

// ThingSpeak
#define THINGSPEAK_API_KEY_1 "YOUR_THINGSPEAK_KEY_1"
#define THINGSPEAK_API_KEY_2 "YOUR_THINGSPEAK_KEY_2"

// Windy
#define WINDY_API_KEY "YOUR_WINDY_API_KEY"
